INSERT INTO RS_USUARIO(ID, NOME, LOGIN, SENHA, EMAIL) VALUES (1, 'Vivian', 'vivian', '13579', 'vivian@gmail.com');
INSERT INTO RS_USUARIO(ID, NOME, LOGIN, SENHA, EMAIL) VALUES (2, 'Alan', 'alan', '24680', 'alan@gmail.com');

ALTER SEQUENCE RS_USUARIO_ID_SEQ RESTART WITH 3;

INSERT INTO RS_PERFIL(ID, DESCRICAO) VALUES(1, 'Administrador');
INSERT INTO RS_PERFIL(ID, DESCRICAO) VALUES(2, 'Gerente');
INSERT INTO RS_PERFIL(ID, DESCRICAO) VALUES(3, 'Cliente');

ALTER SEQUENCE RS_PERFIL_SEQ RESTART WITH 4;